version: '3'
services:
  nginx:
    container_name: nginx_container
    restart: always
    image: nginx
    build:
      context: .
      dockerfile: nginx/Dockerfile
    volumes:
      - ./frontend/dist/Junction2019Frontend:/usr/share/nginx/html
    ports:
      - '80:80'
      - '443:443'
  flask:
    container_name: flask_container
    restart: always
    image: flask
    build: ./backend
    volumes:
      - ./backend:/usr/src/app/server
volumes:
  shared: {}
